package converterControllers

import (
	"bufio"
	. "eaciit/wfdemo-git-dev/library/helper"
	. "eaciit/wfdemo-git-dev/library/models"
	. "eaciit/wfdemo-git-dev/processapp/controllers"
	"encoding/csv"
	"io"
	"os"
	"strings"
	"time"

	_ "github.com/eaciit/dbox/dbc/mongo"
	tk "github.com/eaciit/toolkit"
)

// ConvPermanentMetTowerCSV
type ConvPermanentMetTowerCSV struct {
	*BaseController
}

// Generate
func (d *ConvPermanentMetTowerCSV) Generate(base *BaseController) {
	folderName := "met"
	// funcName := "Converting Met Tower Data"
	count := 0
	total := 0
	errorLine := tk.M{}
	if base != nil {
		d.BaseController = base
		ctx := d.BaseController.Ctx
		_ = ctx
		dataSources, path := base.GetDataSource(folderName)

		// tk.Printf("dataSources: %#v\n", dataSources)

		tk.Println("Converting Met Tower Data from Excel File..")
		for _, source := range dataSources {
			if !strings.Contains(source.Name(), "~") && !strings.Contains(source.Name(), "._") {
				tk.Println(path + "/" + source.Name())
				fr, e := os.Open(path + "/" + source.Name())
				read := csv.NewReader(bufio.NewReader(fr))
				idx := 0
				for {
					record, err := read.Read()
					if err == io.EOF {
						break
					} else if record[0] == "[System]" {
						break
					}
					// tk.Printf("%#v \n", record)
					errorList := []error{}
					if idx > 0 {
						data := new(MetTower).New()
						data.Line = (idx + 1)

						date, _ := time.Parse("2006-01-02 15:04:05", record[0])
						data.TimeStamp = date
						data.DateInfo = GetDateInfo(date)

						data.VHubWS90mAvg, _ = tk.StringToFloat(record[1])
						data.VHubWS90mMax, _ = tk.StringToFloat(record[2])
						data.VHubWS90mMin, _ = tk.StringToFloat(record[3])
						data.VHubWS90mStdDev, _ = tk.StringToFloat(record[4])
						data.VHubWS90mCount, _ = tk.StringToFloat(record[5])
						data.VRefWS88mAvg, _ = tk.StringToFloat(record[6])
						data.VRefWS88mMax, _ = tk.StringToFloat(record[7])
						data.VRefWS88mMin, _ = tk.StringToFloat(record[8])
						data.VRefWS88mStdDev, _ = tk.StringToFloat(record[9])
						data.VRefWS88mCount, _ = tk.StringToFloat(record[10])
						data.VTipWS42mAvg, _ = tk.StringToFloat(record[11])
						data.VTipWS42mMax, _ = tk.StringToFloat(record[12])
						data.VTipWS42mMin, _ = tk.StringToFloat(record[13])
						data.VTipWS42mStdDev, _ = tk.StringToFloat(record[14])
						data.VTipWS42mCount, _ = tk.StringToFloat(record[15])
						data.DHubWD88mAvg, _ = tk.StringToFloat(record[16])
						data.DHubWD88mMax, _ = tk.StringToFloat(record[17])
						data.DHubWD88mMin, _ = tk.StringToFloat(record[18])
						data.DHubWD88mStdDev, _ = tk.StringToFloat(record[19])
						data.DHubWD88mCount, _ = tk.StringToFloat(record[20])
						data.DRefWD86mAvg, _ = tk.StringToFloat(record[21])
						data.DRefWD86mMax, _ = tk.StringToFloat(record[22])
						data.DRefWD86mMin, _ = tk.StringToFloat(record[23])
						data.DRefWD86mStdDev, _ = tk.StringToFloat(record[24])
						data.DRefWD86mCount, _ = tk.StringToFloat(record[25])
						data.THubHHubHumid855mAvg, _ = tk.StringToFloat(record[26])
						data.THubHHubHumid855mMax, _ = tk.StringToFloat(record[27])
						data.THubHHubHumid855mMin, _ = tk.StringToFloat(record[28])
						data.THubHHubHumid855mStdDev, _ = tk.StringToFloat(record[29])
						data.THubHHubHumid855mCount, _ = tk.StringToFloat(record[30])
						data.TRefHRefHumid855mAvg, _ = tk.StringToFloat(record[31])
						data.TRefHRefHumid855mMax, _ = tk.StringToFloat(record[32])
						data.TRefHRefHumid855mMin, _ = tk.StringToFloat(record[33])
						data.TRefHRefHumid855mStdDev, _ = tk.StringToFloat(record[34])
						data.TRefHRefHumid855mCount, _ = tk.StringToFloat(record[35])
						data.THubHHubTemp855mAvg, _ = tk.StringToFloat(record[36])
						data.THubHHubTemp855mMax, _ = tk.StringToFloat(record[37])
						data.THubHHubTemp855mMin, _ = tk.StringToFloat(record[38])
						data.THubHHubTemp855mStdDev, _ = tk.StringToFloat(record[39])
						data.THubHHubTemp855mCount, _ = tk.StringToFloat(record[40])
						data.TRefHRefTemp855mAvg, _ = tk.StringToFloat(record[41])
						data.TRefHRefTemp855mMax, _ = tk.StringToFloat(record[42])
						data.TRefHRefTemp855mMin, _ = tk.StringToFloat(record[43])
						data.TRefHRefTemp855mStdDev, _ = tk.StringToFloat(record[44])
						data.TRefHRefTemp855mCount, _ = tk.StringToFloat(record[45])
						data.BaroAirPress855mAvg, _ = tk.StringToFloat(record[46])
						data.BaroAirPress855mMax, _ = tk.StringToFloat(record[47])
						data.BaroAirPress855mMin, _ = tk.StringToFloat(record[48])
						data.BaroAirPress855mStdDev, _ = tk.StringToFloat(record[49])
						data.BaroAirPress855mCount, _ = tk.StringToFloat(record[50])

						data.YawAngleVoltageAvg, _ = tk.StringToFloat(record[51])
						data.YawAngleVoltageMax, _ = tk.StringToFloat(record[52])
						data.YawAngleVoltageMin, _ = tk.StringToFloat(record[53])
						data.YawAngleVoltageStdDev, _ = tk.StringToFloat(record[54])
						data.YawAngleVoltageCount, _ = tk.StringToFloat(record[55])
						data.OtherSensorVoltageAI1Avg, _ = tk.StringToFloat(record[56])
						data.OtherSensorVoltageAI1Max, _ = tk.StringToFloat(record[57])
						data.OtherSensorVoltageAI1Min, _ = tk.StringToFloat(record[58])
						data.OtherSensorVoltageAI1StdDev, _ = tk.StringToFloat(record[59])
						data.OtherSensorVoltageAI1Count, _ = tk.StringToFloat(record[60])
						data.OtherSensorVoltageAI2Avg, _ = tk.StringToFloat(record[61])
						data.OtherSensorVoltageAI2Max, _ = tk.StringToFloat(record[62])
						data.OtherSensorVoltageAI2Min, _ = tk.StringToFloat(record[63])
						data.OtherSensorVoltageAI2StdDev, _ = tk.StringToFloat(record[64])
						data.OtherSensorVoltageAI2Count, _ = tk.StringToFloat(record[65])
						data.OtherSensorVoltageAI3Avg, _ = tk.StringToFloat(record[66])
						data.OtherSensorVoltageAI3Max, _ = tk.StringToFloat(record[67])
						data.OtherSensorVoltageAI3Min, _ = tk.StringToFloat(record[68])
						data.OtherSensorVoltageAI3StdDev, _ = tk.StringToFloat(record[69])
						data.OtherSensorVoltageAI3Count, _ = tk.StringToFloat(record[70])
						data.OtherSensorVoltageAI4Avg, _ = tk.StringToFloat(record[71])
						data.OtherSensorVoltageAI4Max, _ = tk.StringToFloat(record[72])
						data.OtherSensorVoltageAI4Min, _ = tk.StringToFloat(record[73])
						data.OtherSensorVoltageAI4StdDev, _ = tk.StringToFloat(record[74])
						data.OtherSensorVoltageAI4Count, _ = tk.StringToFloat(record[75])
						data.GenRPMCurrentAvg, _ = tk.StringToFloat(record[76])
						data.GenRPMCurrentMax, _ = tk.StringToFloat(record[77])
						data.GenRPMCurrentMin, _ = tk.StringToFloat(record[78])
						data.GenRPMCurrentStdDev, _ = tk.StringToFloat(record[79])
						data.GenRPMCurrentCount, _ = tk.StringToFloat(record[80])
						data.WS_SCSCurrentAvg, _ = tk.StringToFloat(record[81])
						data.WS_SCSCurrentMax, _ = tk.StringToFloat(record[82])
						data.WS_SCSCurrentMin, _ = tk.StringToFloat(record[83])
						data.WS_SCSCurrentStdDev, _ = tk.StringToFloat(record[84])
						data.WS_SCSCurrentCount, _ = tk.StringToFloat(record[85])
						data.RainStatusCount, _ = tk.StringToFloat(record[86])
						data.RainStatusSum, _ = tk.StringToFloat(record[87])
						data.OtherSensor2StatusIO1Avg, _ = tk.StringToFloat(record[88])
						data.OtherSensor2StatusIO1Max, _ = tk.StringToFloat(record[89])
						data.OtherSensor2StatusIO1Min, _ = tk.StringToFloat(record[90])
						data.OtherSensor2StatusIO1StdDev, _ = tk.StringToFloat(record[91])
						data.OtherSensor2StatusIO1Count, _ = tk.StringToFloat(record[92])
						data.OtherSensor2StatusIO2Avg, _ = tk.StringToFloat(record[93])
						data.OtherSensor2StatusIO2Max, _ = tk.StringToFloat(record[94])
						data.OtherSensor2StatusIO2Min, _ = tk.StringToFloat(record[95])
						data.OtherSensor2StatusIO2StdDev, _ = tk.StringToFloat(record[96])
						data.OtherSensor2StatusIO2Count, _ = tk.StringToFloat(record[97])
						data.OtherSensor2StatusIO3Avg, _ = tk.StringToFloat(record[98])
						data.OtherSensor2StatusIO3Max, _ = tk.StringToFloat(record[99])
						data.OtherSensor2StatusIO3Min, _ = tk.StringToFloat(record[100])
						data.OtherSensor2StatusIO3StdDev, _ = tk.StringToFloat(record[101])
						data.OtherSensor2StatusIO3Count, _ = tk.StringToFloat(record[102])
						data.OtherSensor2StatusIO4Avg, _ = tk.StringToFloat(record[103])
						data.OtherSensor2StatusIO4Max, _ = tk.StringToFloat(record[104])
						data.OtherSensor2StatusIO4Min, _ = tk.StringToFloat(record[105])
						data.OtherSensor2StatusIO4StdDev, _ = tk.StringToFloat(record[106])
						data.OtherSensor2StatusIO4Count, _ = tk.StringToFloat(record[107])
						data.OtherSensor2StatusIO5Avg, _ = tk.StringToFloat(record[108])
						data.OtherSensor2StatusIO5Max, _ = tk.StringToFloat(record[109])
						data.OtherSensor2StatusIO5Min, _ = tk.StringToFloat(record[110])
						data.OtherSensor2StatusIO5StdDev, _ = tk.StringToFloat(record[111])
						data.OtherSensor2StatusIO5Count, _ = tk.StringToFloat(record[112])
						data.A1Avg, _ = tk.StringToFloat(record[113])
						data.A1Max, _ = tk.StringToFloat(record[114])
						data.A1Min, _ = tk.StringToFloat(record[115])
						data.A1StdDev, _ = tk.StringToFloat(record[116])
						data.A1Count, _ = tk.StringToFloat(record[117])
						data.A2Avg, _ = tk.StringToFloat(record[118])
						data.A2Max, _ = tk.StringToFloat(record[119])
						data.A2Min, _ = tk.StringToFloat(record[120])
						data.A2StdDev, _ = tk.StringToFloat(record[121])
						data.A2Count, _ = tk.StringToFloat(record[122])
						data.A3Avg, _ = tk.StringToFloat(record[123])
						data.A3Max, _ = tk.StringToFloat(record[124])
						data.A3Min, _ = tk.StringToFloat(record[125])
						data.A3StdDev, _ = tk.StringToFloat(record[126])
						data.A3Count, _ = tk.StringToFloat(record[127])
						data.A4Avg, _ = tk.StringToFloat(record[128])
						data.A4Max, _ = tk.StringToFloat(record[129])
						data.A4Min, _ = tk.StringToFloat(record[130])
						data.A4StdDev, _ = tk.StringToFloat(record[131])
						data.A4Count, _ = tk.StringToFloat(record[132])
						data.A5Avg, _ = tk.StringToFloat(record[133])
						data.A5Max, _ = tk.StringToFloat(record[134])
						data.A5Min, _ = tk.StringToFloat(record[135])
						data.A5StdDev, _ = tk.StringToFloat(record[136])
						data.A5Count, _ = tk.StringToFloat(record[137])
						data.A6Avg, _ = tk.StringToFloat(record[138])
						data.A6Max, _ = tk.StringToFloat(record[139])
						data.A6Min, _ = tk.StringToFloat(record[140])
						data.A6StdDev, _ = tk.StringToFloat(record[141])
						data.A6Count, _ = tk.StringToFloat(record[142])
						data.A7Avg, _ = tk.StringToFloat(record[143])
						data.A7Max, _ = tk.StringToFloat(record[144])
						data.A7Min, _ = tk.StringToFloat(record[145])
						data.A7StdDev, _ = tk.StringToFloat(record[146])
						data.A7Count, _ = tk.StringToFloat(record[147])
						data.A8Avg, _ = tk.StringToFloat(record[148])
						data.A8Max, _ = tk.StringToFloat(record[149])
						data.A8Min, _ = tk.StringToFloat(record[150])
						data.A8StdDev, _ = tk.StringToFloat(record[151])
						data.A8Count, _ = tk.StringToFloat(record[152])
						data.A9Avg, _ = tk.StringToFloat(record[153])
						data.A9Max, _ = tk.StringToFloat(record[154])
						data.A9Min, _ = tk.StringToFloat(record[155])
						data.A9StdDev, _ = tk.StringToFloat(record[156])
						data.A9Count, _ = tk.StringToFloat(record[157])
						data.A10Avg, _ = tk.StringToFloat(record[158])
						data.A10Max, _ = tk.StringToFloat(record[159])
						data.A10Min, _ = tk.StringToFloat(record[160])
						data.A10StdDev, _ = tk.StringToFloat(record[161])
						data.A10Count, _ = tk.StringToFloat(record[162])
						data.AC1Avg, _ = tk.StringToFloat(record[163])
						data.AC1Max, _ = tk.StringToFloat(record[164])
						data.AC1Min, _ = tk.StringToFloat(record[165])
						data.AC1StdDev, _ = tk.StringToFloat(record[166])
						data.AC1Count, _ = tk.StringToFloat(record[167])
						data.AC2Avg, _ = tk.StringToFloat(record[168])
						data.AC2Max, _ = tk.StringToFloat(record[169])
						data.AC2Min, _ = tk.StringToFloat(record[170])
						data.AC2StdDev, _ = tk.StringToFloat(record[171])
						data.AC2Count, _ = tk.StringToFloat(record[172])
						data.C1Avg, _ = tk.StringToFloat(record[173])
						data.C1Max, _ = tk.StringToFloat(record[174])
						data.C1Min, _ = tk.StringToFloat(record[175])
						data.C1StdDev, _ = tk.StringToFloat(record[176])
						data.C1Count, _ = tk.StringToFloat(record[177])
						data.C2Avg, _ = tk.StringToFloat(record[178])
						data.C2Max, _ = tk.StringToFloat(record[179])
						data.C2Min, _ = tk.StringToFloat(record[180])
						data.C2StdDev, _ = tk.StringToFloat(record[181])
						data.C2Count, _ = tk.StringToFloat(record[182])
						data.C3Avg, _ = tk.StringToFloat(record[183])
						data.C3Max, _ = tk.StringToFloat(record[184])
						data.C3Min, _ = tk.StringToFloat(record[185])
						data.C3StdDev, _ = tk.StringToFloat(record[186])
						data.C3Count, _ = tk.StringToFloat(record[187])
						data.D1Avg, _ = tk.StringToFloat(record[188])
						data.D1Max, _ = tk.StringToFloat(record[189])
						data.D1Min, _ = tk.StringToFloat(record[190])
						data.D1StdDev, _ = tk.StringToFloat(record[191])
						data.M1_1Avg, _ = tk.StringToFloat(record[192])
						data.M1_1Max, _ = tk.StringToFloat(record[193])
						data.M1_1Min, _ = tk.StringToFloat(record[194])
						data.M1_1StdDev, _ = tk.StringToFloat(record[195])
						data.M1_1Count, _ = tk.StringToFloat(record[196])
						data.M1_2Avg, _ = tk.StringToFloat(record[197])
						data.M1_2Max, _ = tk.StringToFloat(record[198])
						data.M1_2Min, _ = tk.StringToFloat(record[199])
						data.M1_2StdDev, _ = tk.StringToFloat(record[200])
						data.M1_2Count, _ = tk.StringToFloat(record[201])
						data.M1_3Avg, _ = tk.StringToFloat(record[202])
						data.M1_3Max, _ = tk.StringToFloat(record[203])
						data.M1_3Min, _ = tk.StringToFloat(record[204])
						data.M1_3StdDev, _ = tk.StringToFloat(record[205])
						data.M1_3Count, _ = tk.StringToFloat(record[206])
						data.M1_4Avg, _ = tk.StringToFloat(record[207])
						data.M1_4Max, _ = tk.StringToFloat(record[208])
						data.M1_4Min, _ = tk.StringToFloat(record[209])
						data.M1_4StdDev, _ = tk.StringToFloat(record[210])
						data.M1_4Count, _ = tk.StringToFloat(record[211])
						data.M1_5Avg, _ = tk.StringToFloat(record[212])
						data.M1_5Max, _ = tk.StringToFloat(record[213])
						data.M1_5Min, _ = tk.StringToFloat(record[214])
						data.M1_5StdDev, _ = tk.StringToFloat(record[215])
						data.M1_5Count, _ = tk.StringToFloat(record[216])
						data.M2_1Avg, _ = tk.StringToFloat(record[217])
						data.M2_1Max, _ = tk.StringToFloat(record[218])
						data.M2_1Min, _ = tk.StringToFloat(record[219])
						data.M2_1StdDev, _ = tk.StringToFloat(record[220])
						data.M2_1Count, _ = tk.StringToFloat(record[221])
						data.M2_2Avg, _ = tk.StringToFloat(record[222])
						data.M2_2Max, _ = tk.StringToFloat(record[223])
						data.M2_2Min, _ = tk.StringToFloat(record[224])
						data.M2_2StdDev, _ = tk.StringToFloat(record[225])
						data.M2_2Count, _ = tk.StringToFloat(record[226])
						data.M2_3Avg, _ = tk.StringToFloat(record[227])
						data.M2_3Max, _ = tk.StringToFloat(record[228])
						data.M2_3Min, _ = tk.StringToFloat(record[229])
						data.M2_3StdDev, _ = tk.StringToFloat(record[230])
						data.M2_3Count, _ = tk.StringToFloat(record[231])
						data.M2_4Avg, _ = tk.StringToFloat(record[232])
						data.M2_4Max, _ = tk.StringToFloat(record[233])
						data.M2_4Min, _ = tk.StringToFloat(record[234])
						data.M2_4StdDev, _ = tk.StringToFloat(record[235])
						data.M2_4Count, _ = tk.StringToFloat(record[236])
						data.M2_5Avg, _ = tk.StringToFloat(record[237])
						data.M2_5Max, _ = tk.StringToFloat(record[238])
						data.M2_5Min, _ = tk.StringToFloat(record[239])
						data.M2_5StdDev, _ = tk.StringToFloat(record[240])
						data.M2_5Count, _ = tk.StringToFloat(record[241])
						data.M2_6Avg, _ = tk.StringToFloat(record[242])
						data.M2_6Max, _ = tk.StringToFloat(record[243])
						data.M2_6Min, _ = tk.StringToFloat(record[244])
						data.M2_6StdDev, _ = tk.StringToFloat(record[245])
						data.M2_6Count, _ = tk.StringToFloat(record[246])
						data.M2_7Avg, _ = tk.StringToFloat(record[247])
						data.M2_7Max, _ = tk.StringToFloat(record[248])
						data.M2_7Min, _ = tk.StringToFloat(record[249])
						data.M2_7StdDev, _ = tk.StringToFloat(record[250])
						data.M2_7Count, _ = tk.StringToFloat(record[251])
						data.M2_8Avg, _ = tk.StringToFloat(record[252])
						data.M2_8Max, _ = tk.StringToFloat(record[253])
						data.M2_8Min, _ = tk.StringToFloat(record[254])
						data.M2_8StdDev, _ = tk.StringToFloat(record[255])
						data.M2_8Count, _ = tk.StringToFloat(record[256])
						data.VAvg, _ = tk.StringToFloat(record[257])
						data.VMax, _ = tk.StringToFloat(record[258])
						data.VMin, _ = tk.StringToFloat(record[259])
						data.IAvg, _ = tk.StringToFloat(record[260])
						data.IMax, _ = tk.StringToFloat(record[261])
						data.IMin, _ = tk.StringToFloat(record[262])
						data.T, _ = tk.StringToFloat(record[263])
						data.Addr, _ = tk.StringToFloat(record[264])

						if e != nil {
							errorLine.Set(tk.ToString(idx+1), errorList)
						} else {
							e = ctx.Insert(data)
						}
					}
					idx++
				}

				total += count
				tk.Printf("count: %v \n", total)
				tk.Printf("count line error: %v \n", len(errorLine))
				if len(errorLine) > 0 {
					WriteErrors(errorLine, source.Name())
				}
			}
		}
	}
}
